server:
  port: 8082
spring:
  application:
    name: schedule
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/schedule
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        globally_quoted_identifiers: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    kafka:
      bootstrap-servers: localhost:9092